export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_PROD_BY_DEPT_ID = "SET_PROD_BY_DEPT_ID"
export const SET_PRODUCT_BY_CATEGORY_ID = 'SET_PRODUCT_BY_CATEGORY_ID';
export const SET_PRODUCT_BY_ID = "SET_PRODUCT_BY_ID";